
#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.springms: DEBUG
    com.dcjinchan.jcmes.schedulemap: DEBUG
#####################################################################################################
